### ISSUE TITLE
Add conference call information

### ISSUE THREAD

**Issue by sebasrp** [gaqzi/incident-commander#1]
As an incident commander, I want to make sure i can add the conference call information in an incident, and later easily copy and paste it when needed.

**Comment by gaqzi** [comment]
This has been added and is now at the very end as a `Links` section.

Example output:

```
*Investigating* Since 10:00 UTC we are seeing Paypal unavailable in TW impacting 2% of orders 100% of Paypal customers.

*Current status:*
- 🔴 Paypal unavailable
- ✅ Peering with Comcast

*Links:*
- [m000](https://m000s.com/)
```
