### ISSUE TITLE
Add a test suite

### ISSUE THREAD

**Issue by gaqzi** [gaqzi/incident-commander#15]
The MVP was cowboy coded by @gaqzi to see how it would work. If we start using it, we'll encourage people to participate in coding as well, and we need to have a clear mechanism for collaborating.

Which will require tests, so we don't break something. And since we intend to use this software during incidents, i.e., a time when mistakes are costly, we *need* to make sure within reason we don't introduce bugs.

**Comment by gabehollombe** [comment]
We have an e2e test suite via `npx cypress run` now. Closing.
