### ISSUE TITLE
Come up with a plan for how to do multiplayer

### ISSUE THREAD

**Issue by gaqzi** [gaqzi/incident-commander#18]
From the start I decided to use events to communicate across components on the page because… that's what I'm used to doing. But I also knew that it would allow us to take that mechanism and _relatively_ easily turn it into something that could be used to send and replay events for others.

So decide on how we'll do it:

- The interface of a backend
    - What do we expect a backend to do? (pure event playback? aggregate events?)
- How will the events be structured?
- How will we handle multiple versions of the UI/events?
    - Or, how do we ensure we don't break backward compatibility?
- How will we ensure the client and the backend are in agreement? (Pact?)

**Comment by gaqzi** [comment]
@gabehollombe and I were talking about possible ways of implementing this:

The thing that would make multiplayer immediately useful is if you had a known incident ID and could start sharing changes. Would we need to build a server or could we use P2P solutions without? And how do we sync between?

- [ShareDB](https://github.com/share/sharedb) is a realtime database backend based on [Operational Transformation (OT)](https://en.wikipedia.org/wiki/Operational_transformation) of JSON documents. It is the realtime backend for the [DerbyJS web application framework](http://derbyjs.com/).
    - Looks like a nifty solution to sync JSON and relies on a websocket server to mediate
- [YJS](https://docs.yjs.dev/getting-started/working-with-shared-types) is a library that's built for rich text editors (and code, and so on) but also provides primitives to sync JSON overall
    - It's very focused on text and maybe taking on a lot of stuff when we don't need it. But it does have the core types which might be fine since we're doing events appended to an array
- "Build our own"
    - A lambda that takes events, batches by incident, and writes to a JSON document with the correct cache control headers probably to S3. That way we have something super basic, longterm archival, and something to work with.
    - Can really go any direction

To start with, it's not necessarily important to have an "archival sink" because it's all about fixing something that's on fire and getting people collaborating. Those that were part should be able to have the incident on their machine and they should be able to use the tool to help with reports. But syncing to archive is a nice to have.

**Comment by gabehollombe** [comment]
I integrated YJS and it seems like it works, so let's close this for now.
