### ISSUE TITLE
Buttons "Business Update" and "Tech update" do not work

### ISSUE THREAD

**Issue by sebasrp** [gaqzi/incident-commander#2]
**What?**
When clicking the buttons "Business Update" or "Tech update", the url of the page is copied (`https://gaqzi.github.io/incident-commander/`)

**Expected**
When clicking the buttons, i expect the latest "business update" or latest summary of tech actions to be copied

**Comment by gaqzi** [comment]
This is now available in the latest version, please give it a whirl!
