### ISSUE TITLE
Document the event schema and conventions

### ISSUE THREAD

**Issue by gaqzi** [gaqzi/incident-commander#23]
The events right now are not very thought out and need to be defined clearly so they can grow:

- What does the envelope contain?
- How will we indicate related events? For example, Create -> Update -> Delete/Resolve, are all related to one item. Today we set the ID to the same for each event and rely on the `recordedAt` time, but that doesn't feel very good.
- What is the schema of individual events
- What naming conventions will we use? (Active/passive? Subject-Verb or Verb-Subject?
- What are the default verbs we're using to describe things?

**Comment by gabehollombe** [comment]
Do you think the types at the top of https://github.com/gaqzi/incident-commander/blob/master/app/components/ongoing-incident/reducer.tsx#L5 and the `switch` at https://github.com/gaqzi/incident-commander/blob/master/app/components/ongoing-incident/reducer.tsx#L198  is enough for now? It's not documented but I'm not sure it _needs_ to be more documented than the current code.

**Comment by gaqzi** [comment]
sounds fair, I was mostly thinking of doing something for when we involve a backend (which in my original plan was much earlier but with all the js sharing magic that got skipped :D)

as long as we're just doing it in the browser and we're clear about not breaking anything it doesn't matter…

**Comment by gabehollombe** [comment]
Ok let's close this and revisit if/when we want a real backend because I agree, it's much more important then!
