### ISSUE TITLE
Figure out how to handle updates

### ISSUE THREAD

**Issue by gaqzi** [gaqzi/incident-commander#25]
So far, I have used right-clicking to pop up a `prompt` or a `<dialog>` to ask for input. The dialog feels like a better option for getting the data. But right-clicking is probably wrong? Should it be double-clicking? Edit icons for full sections? 

Decide on what kind of interactions and then update it consistently across.

**Comment by gabehollombe** [comment]
Most interactions have moved to icons for discoverability which either do the thing or show an action menu on hover. Only ones remaining without are:

- Summary at the top (I think we should just add a little pencil icon next to the summary')
- Action timer (which requires hover, but we do have a little clock icon there, so maybe enough as-is?)

Thoughts?

**Comment by gaqzi** [comment]
sounds good to me!

And probably should move away from using `prompt()` because it's not super nice, we still have some uses of it, right?

**Comment by gabehollombe** [comment]
We have one use of prompt (for when you mark action as failed). It actually feels OK (not great) for me. Got the job done, less work than putting another modal in place with a form field bound to one more state var in a react component, but if you want later, make an issue for removing the last prompt and we'll do it =)
